# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='asset',
            field=models.ManyToManyField(blank=True, to='app_crm.Asset'),
        ),
    ]
