# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='facebook',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='linkedin',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='street2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='twitter',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='website',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
