# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0002_auto_20161118_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Is This a Company?'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
